default: &default
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  prerender_io_token: <%= ENV["PRERENDER_IO_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test: *default
development: *default
staging: *default
production: *default
